[package]
authors = ['Daniel Olano <daniel@olanod.com>']
edition = '2018'
homepage = 'https://github.com/valibre-org/node'
license = 'Unlicense'
name = 'vln-runtime'
repository = 'https://github.com/valibre-org/node'
version = '2.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-wasm-builder = '4.0.0'

[dependencies]
codec = {package = 'parity-scale-codec', version = '2.0.0', default-features = false, features = ['derive']}
serde = {version = '1.0.124', optional = true, features = ['derive']}
hex-literal = {version = '0.3.1', optional = true}

# Substrate dependencies
sp-api = {git = 'https://github.com/paritytech/substrate', default-features = false, branch = 'polkadot-v0.9.3'}
sp-io = {git = 'https://github.com/paritytech/substrate', default-features = false, branch = 'polkadot-v0.9.3'}
sp-block-builder = {git = 'https://github.com/paritytech/substrate', default-features = false, branch = 'polkadot-v0.9.3'}
sp-core = {git = 'https://github.com/paritytech/substrate', default-features = false, branch = 'polkadot-v0.9.3'}
sp-inherents = {git = 'https://github.com/paritytech/substrate', default-features = false, branch = 'polkadot-v0.9.3'}
sp-offchain = {git = 'https://github.com/paritytech/substrate', default-features = false, branch = 'polkadot-v0.9.3'}
sp-runtime = {git = 'https://github.com/paritytech/substrate', default-features = false, branch = 'polkadot-v0.9.3'}
sp-session = {git = 'https://github.com/paritytech/substrate', default-features = false, branch = 'polkadot-v0.9.3'}
sp-std = {git = 'https://github.com/paritytech/substrate', default-features = false, branch = 'polkadot-v0.9.3'}
sp-transaction-pool = {git = 'https://github.com/paritytech/substrate', default-features = false, branch = 'polkadot-v0.9.3'}
sp-version = {git = 'https://github.com/paritytech/substrate', default-features = false, branch = 'polkadot-v0.9.3'}
frame-executive = {git = 'https://github.com/paritytech/substrate', default-features = false, branch = 'polkadot-v0.9.3'}
frame-support = {git = 'https://github.com/paritytech/substrate', default-features = false, branch = 'polkadot-v0.9.3'}
frame-system = {git = 'https://github.com/paritytech/substrate', default-features = false, branch = 'polkadot-v0.9.3'}
pallet-randomness-collective-flip = {git = 'https://github.com/paritytech/substrate', default-features = false, branch = 'polkadot-v0.9.3'}
pallet-sudo = {git = 'https://github.com/paritytech/substrate', default-features = false, branch = 'polkadot-v0.9.3'}
pallet-timestamp = {git = 'https://github.com/paritytech/substrate', default-features = false, branch = 'polkadot-v0.9.3'}
frame-benchmarking = {git = 'https://github.com/paritytech/substrate', default-features = false, optional = true, branch = 'polkadot-v0.9.3'}
frame-system-benchmarking = {git = 'https://github.com/paritytech/substrate', default-features = false, optional = true, branch = 'polkadot-v0.9.3'}
frame-system-rpc-runtime-api = {git = 'https://github.com/paritytech/substrate', default-features = false, branch = 'polkadot-v0.9.3'}
sp-consensus-aura = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.3', default-features = false, version = '0.9.0' }
pallet-grandpa = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.3', default-features = false }
pallet-aura = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.3', default-features = false }
pallet-assets = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.3', default-features = false }
pallet-balances = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.3', default-features = false }
pallet-transaction-payment = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.3', default-features = false }
pallet-transaction-payment-rpc-runtime-api = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.3', default-features = false }

# Cumulus dependencies
cumulus-pallet-parachain-system = {git = 'https://github.com/paritytech/cumulus', default-features = false, branch = 'polkadot-v0.9.3'}
cumulus-primitives-core = {git = 'https://github.com/paritytech/cumulus', default-features = false, branch = 'polkadot-v0.9.3'}
parachain-info = {git = 'https://github.com/paritytech/cumulus', default-features = false, branch = 'polkadot-v0.9.3'}
cumulus-pallet-aura-ext = { git = 'https://github.com/paritytech/cumulus', branch = 'polkadot-v0.9.3', default-features = false }
# xcm = {git = 'https://github.com/paritytech/polkadot', default-features = false, branch = 'polkadot-v0.9.3'}
# xcm-builder = {git = 'https://github.com/paritytech/polkadot', default-features = false, branch = 'release-v0.9.3'}
# xcm-executor = {git = 'https://github.com/paritytech/polkadot', default-features = false, branch = 'release-v0.9.3'}
polkadot-parachain = {git = 'https://github.com/paritytech/polkadot', default-features = false, branch = 'release-v0.9.3'}
# cumulus-primitives-utility = {git = 'https://github.com/paritytech/cumulus', default-features = false, branch = 'polkadot-v0.9.3'}
# cumulus-pallet-xcm = {git = 'https://github.com/paritytech/cumulus', default-features = false, branch = 'polkadot-v0.9.3'}
# cumulus-pallet-xcmp-queue = {git = 'https://github.com/paritytech/cumulus', default-features = false, branch = 'polkadot-v0.9.3'}
# pallet-xcm = {git = 'https://github.com/paritytech/polkadot', default-features = false, branch = 'polkadot-v0.9.3'}

# Vln dependencies
orml-traits = { git = 'https://github.com/valibre-org/open-runtime-module-library', default-features = false }
orml-oracle = { git = 'https://github.com/valibre-org/open-runtime-module-library', default-features = false }
pallet-proxy = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.3', default-features = false }
pallet-membership = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.3', default-features = false }
# orml-xtokens = { git = 'https://github.com/valibre-org/open-runtime-module-library', default-features = false }
# orml-xcm-support = { git = 'https://github.com/valibre-org/open-runtime-module-library', default-features = false }
# orml-unknown-tokens = { git = 'https://github.com/valibre-org/open-runtime-module-library', default-features = false }

# Local dependencies
vln-primitives = { default-features = false, path = '../primitives' }
vln-rate-provider = { default-features = false, path = '../pallets/rate_provider' }
vln-escrow = { default-features = false, path = '../pallets/escrow' }

[features]
default = ['std']
runtime-benchmarks = [
    'sp-runtime/runtime-benchmarks',
    'frame-benchmarking',
    'frame-support/runtime-benchmarks',
    'frame-system-benchmarking',
    'hex-literal',
    'frame-system/runtime-benchmarks',
    'pallet-timestamp/runtime-benchmarks',
]
std = [
	'codec/std',
	'serde',
	'sp-api/std',
	'sp-std/std',
	'sp-io/std',
	'sp-core/std',
	'sp-runtime/std',
	'sp-version/std',
	'sp-offchain/std',
	'sp-session/std',
	'sp-block-builder/std',
	'sp-transaction-pool/std',
	'pallet-aura/std',
	'frame-support/std',
	'frame-executive/std',
	'frame-system/std',
	'frame-system-rpc-runtime-api/std',
	'sp-consensus-aura/std',
	'pallet-grandpa/std',
	'pallet-randomness-collective-flip/std',
	'pallet-timestamp/std',
	'pallet-sudo/std',
	'parachain-info/std',
	'cumulus-pallet-parachain-system/std',
	'cumulus-primitives-core/std',
    'orml-oracle/std',
	'pallet-proxy/std',
	'vln-primitives/std',
	'pallet-membership/std',
	'vln-escrow/std',
	'cumulus-pallet-aura-ext/std',
	'vln-rate-provider/std',
	# 'orml-xtokens/std',
	# 'orml-xcm-support/std',
	# 'orml-unknown-tokens/std',
	# 'cumulus-pallet-xcmp-queue/std',
	# 'cumulus-pallet-xcm/std',
	# 'xcm/std',
	# 'xcm-builder/std',
	# 'xcm-executor/std',
	# 'cumulus-pallet-xcm-handler/std',
	'pallet-assets/std',
	'pallet-balances/std',
	'pallet-assets/std',
	'pallet-transaction-payment-rpc-runtime-api/std',
	'pallet-transaction-payment/std'
]
standalone = []

