[package]
authors = ['Daniel Olano <daniel@olanod.com>']
edition = '2018'
homepage = 'https://github.com/valibre-org/node'
license = 'Unlicense'
name = 'vln-runtime'
repository = 'https://github.com/valibre-org/node'
version = '2.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1", version = '4.0.0' }

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"]}
serde = {version = "1.0.101", optional = true, features = ["derive"]}
hex-literal = {version = "0.3.1", optional = true}

# Substrate dependencies
sp-api = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1", version = '3.0.0'}
sp-io = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1", version = '3.0.0'}
sp-block-builder = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1", version = '3.0.0'}
sp-core = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1", version = '3.0.0'}
sp-inherents = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1", version = '3.0.0'}
sp-offchain = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1", version = '3.0.0'}
sp-runtime = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1", version = '3.0.0'}
sp-session = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1", version = '3.0.0'}
sp-std = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1", version = '3.0.0'}
sp-transaction-pool = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1", version = '3.0.0'}
sp-version = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1", version = '3.0.0'}
frame-executive = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1", version = '3.0.0'}
frame-support = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1", version = '3.0.0'}
frame-system = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1", version = '3.0.0'}
pallet-randomness-collective-flip = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1", version = '3.0.0'}
pallet-sudo = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1", version = '3.0.0'}
pallet-timestamp = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1", version = '3.0.0'}
frame-benchmarking = {git = "https://github.com/paritytech/substrate", default-features = false, optional = true, branch = "rococo-v1", version = '3.0.0'}
frame-system-benchmarking = {git = "https://github.com/paritytech/substrate", default-features = false, optional = true, branch = "rococo-v1", version = '3.0.0'}
frame-system-rpc-runtime-api = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1", version = '3.0.0'}
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false, version = '0.9.0' }
pallet-grandpa = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false, version = '3.0.0' }
pallet-aura = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false, version = '3.0.0' }

# Cumulus dependencies
cumulus-pallet-parachain-system = {git = "https://github.com/paritytech/cumulus", default-features = false, branch = "rococo-v1"}
cumulus-primitives-core = {git = "https://github.com/paritytech/cumulus", default-features = false, branch = "rococo-v1"}
parachain-info = {git = "https://github.com/paritytech/cumulus", default-features = false, branch = "rococo-v1"}
xcm = {git = "https://github.com/paritytech/polkadot", default-features = false, branch = "rococo-v1"}
xcm-builder = {git = "https://github.com/paritytech/polkadot", default-features = false, branch = "rococo-v1"}
xcm-executor = {git = "https://github.com/paritytech/polkadot", default-features = false, branch = "rococo-v1"}
cumulus-pallet-xcm-handler = {git = "https://github.com/paritytech/cumulus", default-features = false, branch = "rococo-v1"}
polkadot-parachain = {git = "https://github.com/paritytech/polkadot", default-features = false, branch = "rococo-v1"}

# Vln dependencies
orml-tokens = { git = "https://github.com/valibre-org/open-runtime-module-library", default-features = false, version = "0.4.1-dev", branch = "instantiable_tokens_pallet" }
orml-traits = { git = "https://github.com/valibre-org/open-runtime-module-library", default-features = false, version = "0.4.1-dev", branch = "instantiable_tokens_pallet"  }
orml-oracle = { git = "https://github.com/valibre-org/open-runtime-module-library", default-features = false, version = "0.4.1-dev", branch = "instantiable_tokens_pallet"  }
pallet-proxy = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false, version = '3.0.0' }

# Local dependencies
vln-primitives = { default-features = false, path = '../primitives' }
vln-foreign-asset = { default-features = false, path = '../pallets/foreign_asset' }
vln-backed-asset = { default-features = false, path = '../pallets/backed_asset' }
vln-human-swap = { default-features = false, path = '../pallets/human_swap' }
vln-transfers = { default-features = false, path = '../pallets/transfers' }

[features]
default = ['std']
runtime-benchmarks = [
    'sp-runtime/runtime-benchmarks',
    'frame-benchmarking',
    'frame-support/runtime-benchmarks',
    'frame-system-benchmarking',
    'hex-literal',
    'frame-system/runtime-benchmarks',
    'pallet-timestamp/runtime-benchmarks',
]
std = [
	"codec/std",
	"serde",
	"sp-api/std",
	"sp-std/std",
	"sp-io/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-version/std",
	"sp-offchain/std",
	"sp-session/std",
	"sp-block-builder/std",
	"sp-transaction-pool/std",
	'pallet-aura/std',
	"frame-support/std",
	"frame-executive/std",
	"frame-system/std",
	"frame-system-rpc-runtime-api/std",
	"sp-consensus-aura/std",
	"pallet-grandpa/std",
	"pallet-randomness-collective-flip/std",
	"pallet-timestamp/std",
	"pallet-sudo/std",
	"parachain-info/std",
	"cumulus-pallet-parachain-system/std",
	"cumulus-primitives-core/std",
	"xcm/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"cumulus-pallet-xcm-handler/std",
	'orml-tokens/std',
    'orml-oracle/std',
	'pallet-proxy/std',
	'vln-primitives/std',
    'vln-foreign-asset/std',
    'vln-backed-asset/std',
    'vln-human-swap/std',
    'vln-transfers/std',
]
standalone = []
